/**
 * Pure JSON -> SQL transformation for safety_content, with no filesystem or
 * process access. Kept separate from build-safety-content-seed.mjs (the CLI
 * entrypoint) so it can be imported into Jest without needing to handle
 * import.meta or any of Node's ESM-loader-only globals.
 */
import { validateContent } from "./contentValidate.mjs";

const q = (value) =>
  value === null || value === undefined ? "NULL" : `'${String(value).replace(/'/g, "''")}'`;

const jsonb = (value) => `${q(JSON.stringify(value ?? []))}::jsonb`;

export function toSql(items) {
  const errors = validateContent(items);
  if (errors.length > 0) {
    throw new Error(`Refusing to generate SQL:\n  ${errors.join("\n  ")}`);
  }

  const header = [
    "-- Generated by app/scripts/build-safety-content-seed.mjs. Do not hand-edit.",
    "-- Source of truth: app/src/data/safety-content.bundled.json",
    "",
  ].join("\n");

  const rows = items.map((item) => {
    const r = item.review ?? {};
    return `INSERT INTO safety_content (
    slug, category, subcategory, title, summary, body,
    steps, tags, contextual_trigger, sources, content_hash,
    review_state, reviewer_name, reviewer_credential, last_reviewed, reviewed_content_hash
) VALUES (
    ${q(item.slug)},
    ${q(item.category)},
    ${q(item.subcategory)},
    ${q(item.title)},
    ${q(item.summary)},
    ${q(item.body)},
    ${jsonb(item.steps)},
    ${jsonb(item.tags)},
    ${q(item.contextual_trigger)},
    ${jsonb(item.sources)},
    ${q(item.content_hash)},
    ${q(r.state)},
    ${q(r.reviewer_name ?? null)},           -- reviewer_name
    ${q(r.reviewer_credential ?? null)},     -- reviewer_credential
    ${r.reviewed_at ? q(r.reviewed_at) + "::timestamptz" : "NULL"},
    ${q(r.content_hash ?? null)}
) ON CONFLICT (slug) DO UPDATE SET
    category = EXCLUDED.category,
    subcategory = EXCLUDED.subcategory,
    title = EXCLUDED.title,
    summary = EXCLUDED.summary,
    body = EXCLUDED.body,
    steps = EXCLUDED.steps,
    tags = EXCLUDED.tags,
    contextual_trigger = EXCLUDED.contextual_trigger,
    sources = EXCLUDED.sources,
    content_hash = EXCLUDED.content_hash,
    review_state = EXCLUDED.review_state,
    reviewer_name = EXCLUDED.reviewer_name,
    reviewer_credential = EXCLUDED.reviewer_credential,
    last_reviewed = EXCLUDED.last_reviewed,
    reviewed_content_hash = EXCLUDED.reviewed_content_hash;
`;
  });

  return `${header}${rows.join("\n")}`;
}
